<a href="https://colab.research.google.com/github/mehulmalgaonkar/code1/blob/master/python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("vadapav")

vadapav


In [ ]:
if True:
   print("true")
else:
   print("false")

true


In [ ]:
#comment
"""
comment
"""
print("vadapav")


vadapav


In [ ]:
count = 123
dist = 1000.0
f_name = "mehul"
print(f_name)
print(dist)
print(count)

mehul
1000.0
123


In [ ]:
x=y=z="vada"
a,b,c="va","da","pav"
m,n,o=1,2,3
print(x)
print(y)
print(z)
print(a)
print(b)
print(c)
print(x+c)
print(m+o)
print(x+"o")

vada
vada
vada
va
da
pav
vadapav
4
vadao


# Standard built

In [ ]:
x=123
y="vada pav"
z=2.0
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'str'>
<class 'float'>


In [ ]:
x="this is a cat"
print(x)
print (x[2:5])  #prints from 3 to 5
print (x[2:])   #prints from 3 
print(x*2)

this is a cat
is 
is is a cat
this is a catthis is a cat


CONDITION STATEMENTS

In [ ]:
a,b=2,3
if a>b:
 print("a is greater")
elif a<b:                     #else if statement(2nd condition)
 print("b is greater")
else:
 print("a and b are equal")


b is greater


In [ ]:
a,b=2,3
print ("A") if a>b else print ("=") if a==b else print("B")    #short condition

B


In [ ]:
a,b,c=1,3,2
if a<b and c>a:                           #if 1st statement and 2nd statement is true then execute 
 print ("both conditions are true")
if a<b or c<a:                            #if 1st statement or 2nd statement is true then execute 
  print ("atleast one condition is true")

both conditions are true
atleast one condition is true


In [ ]:
x=15
if x>10:
  print("it is greater than 10")
  if x>20:                            #nested if condition
    print("it is greater than 20")
  else:
    print("it is not greater than 20")
else:
  print("it is not greater than 10")

it is greater than 10
it is not greater than 20


LOOPS

In [ ]:
i=1
while i<=10:          #while loop
  print(i*2)
  i+=1

2
4
6
8
10
12
14
16
18
20


In [ ]:
i=1
while i<=10:
  print(i)
  if i==3:
    break         #breaks the loop
  i+=1

1
2
3


In [ ]:
i=1
while i<=10:
  i+=1
  if i==3:
    continue         #continues the loop(skips the following statement)
  print(i)


2
4
5
6
7
8
9
10
11


In [ ]:
i=1
while i<=5:          #while loop
  print(i)
  i+=1
else:
  print("condition fulfilled")

1
2
3
4
5
condition fulfilled


In [ ]:
fruits=["orange","apple","banana"]
for x in fruits:                    #for loop
  print(x) 

orange
apple
banana


In [ ]:
for x in "banana": #also works with string
  print(x)

b
a
n
a
n
a


In [ ]:
for x in range(6):    #range function
  print(x)
else:                 #else can also be used
  print(range(6))

0
1
2
3
4
5
range(0, 6)


In [ ]:
color=["red","green","yellow"]
fruits=["orange","apple","banana"]
for x in color:                    #for loop
  for y in fruits:                    #inner for loop
    print(x,y) 
  

red orange
red apple
red banana
green orange
green apple
green banana
yellow orange
yellow apple
yellow banana


INPUT

In [ ]:
x=input("enter value")
x=float(x)
print(x)

enter value5
5.0


FUNCTIONS

In [ ]:
def func():            #defining the function
  print("vadapav")
func()                 #calling the function

vadapav


In [ ]:
def func(x):            #defining the function
  print(x +"pav")
func("vada")  
func("samosa") 

vadapav
samosapav


In [ ]:
def func(x):            #defining the function
  print(x[0] +"pav")
func(["vada","samosa"])

vadapav


In [ ]:
def func(x="vada"):            #defining the function with default value
  print(x +"pav")
func()  
func("samosa") 

vadapav
samosapav


In [ ]:
def func(x):            #defining the function
  return 5+x              #returns value 
func(5) 

10

In [ ]:
x= lambda a,b:a*b #lambda function can have n no. of arguments but only one expression
print(x(5,6))

30


CLASS AND OBJECT

In [ ]:
class car:                  #creating a class
  year=2016
  mpg=20
  speed=100
  def accelerate(self):
    return car.speed+20
  def brake(self):
    return car.speed-50
car1=car()                   #creating an object
print(car1.accelerate())
print(car1.brake())
print(car1.year)
print(car1.mpg)
print(car1.speed)

120
50
2016
20
100


EXCEPTION HANDELING

In [ ]:
 try:
   x=4
   print(x/0)

except:
  print("An error occured")


An error occured


In [ ]:
try:
  print(a)

except NameError:
  print("VARIABLE ERROR")
except:
  print("ERROR")
else:
  print("SUCCESS")

VARIABLE ERROR


RegEX(regular expression)

In [ ]:
import re

In [ ]:
txt ="the rain in spain"
x= re.search("^the.*spain$",txt) #regex to search for a word
print(x)

<re.Match object; span=(0, 17), match='the rain in spain'>


In [ ]:
txt ="the rain in spain"
x= re.findall("ai",txt) #regex to search for all occurences
print(x)
print(len(x))

['ai', 'ai']
2


In [ ]:
txt ="the rain in spain"
x= re.search("\s",txt)
print("the first space is at:",x.start())

the first space is at: 3


In [ ]:
txt ="the rain in spain"
x= re.split("\s",txt)
print(x)
x= re.split("\s",txt,1)
print(x)

['the', 'rain', 'in', 'spain']
['the', 'rain in spain']


In [ ]:
txt ="the rain in spain"
x= re.sub("\s","-",txt)
print(x)
x= re.sub("\s","-",txt,2)
print(x)

the-rain-in-spain
the-rain-in spain


In [ ]:
line="cats are rarer than dogs"
mo=re.match(r'(.*)are(.*?) .*',line,re.M|re.I)#re,M-multiline search,re.I-sreach without case(ignore case)
print(mo)
if mo:
  print("mo.group():",mo.group())
  print("mo.group(1):",mo.group(1))
  print("mo.group(2):",mo.group(2))
else:
  print("No matches!")

<re.Match object; span=(0, 24), match='cats are rarer than dogs'>
mo.group(): cats are rarer than dogs
mo.group(1): cats are r
mo.group(2): r


##Numpy

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr[1:3])    #to slice an array
print(arr[2:])
print(arr[1:4:2])  #to print alternate elements

[1 2 3 4 5]
[2 3]
[3 4 5]
[2 4]


In [ ]:
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(5,)


In [ ]:
a=np.array(1)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)
print(b)
print(c)
print(d)


1
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
newarr=arr.reshape(4,3)
print(newarr)

NameError: ignored

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
for x in a:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
c=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,1],[4,6,5]])
a=np.concatenate(c,b,axis=0,out=None)
print(a)

TypeError: ignored

##Pandas

In [ ]:
import pandas as pd
mydataset={'cars':["BMW","Volvo","Ford"],
           'quantity':[3,7,2]}
myvar=pd.DataFrame(mydataset)
print(mydataset)
print(myvar)

{'cars': ['BMW', 'Volvo', 'Ford'], 'quantity': [3, 7, 2]}
    cars  quantity
0    BMW         3
1  Volvo         7
2   Ford         2
